---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
      - pandas.awesome.bears.example
    providers:
      # the ordering of the encryption providers array is important
      # the first provider will provide the encryption
      # if identity: {} is placed first, means no encryption
      - aescbc:
          keys:
            - name: key1
              # See the following text for more details about the secret value
              # this is the encryption key
              secret: <BASE 64 ENCODED SECRET>
      - identity: {} # this fallback allows reading unencrypted secrets;
                     # for example, during initial migration