apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  backoffLImit: 20   #total number of times to try with backoff
  completions: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never

